# Available Variables:
# <NAME> Player's name
# <WORLD> World name
# <X> X coordinate
# <Y> Y Coordinate
# <Z> Z coordinate
# <N> Switches to next line
# <PLAYERS> Number of players online
# <MAXPLAYERS> Max amount of players
# <PING> Player's ping
# <TPS> Server TPS
# <FNAME> Faction name
# <MONEY> Money amount from EconomyAPI

Message: "XHud 3.0<N>Created by PetteriM1<N>You can edit hud in config.yml<N><N><N>"

UpdateIntervalTicks: 10
